name: Publish to NPM
on: workflow_dispatch

jobs:
  publish-npm-backup:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --scope=@lunaticmuch --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
